### ISSUE TITLE
[BUG] Server crash in Exiled.Events.EventArgs.Player.DyingEventArgs

### ISSUE THREAD

**Issue by ITeMbI4** [Exiled-Team/EXILED#2116]
**Describe the bug**
Get this bug only once, when server just crashed.
```
[2023-09-23 09:58:23.917 +00:00] [STDOUT] Caught fatal signal - signo:11 code:2 errno:0 addr:0x40a930
[2023-09-23 09:58:23.919 +00:00] [STDOUT] Obtained 5 stack frames.
[2023-09-23 09:58:23.919 +00:00] [STDOUT] #0  0x007f0e417b9140 in funlockfile
[2023-09-23 09:58:23.919 +00:00] [STDOUT] #1  0x0000000040a930 in (Unknown)
[2023-09-23 09:58:23.919 +00:00] [STDOUT] #2  0x00000041d17a00 in System.Linq.Expressions.Expression:Property (System.Linq.Expressions.Expression,System.Reflection.PropertyInfo)
[2023-09-23 09:58:23.919 +00:00] [STDOUT] #3  0x00000041f1881c in Player_Statistic.PlayerChanges:Target (Exiled.Events.EventArgs.Player.DyingEventArgs)
[2023-09-23 09:58:23.919 +00:00] [STDOUT] #4  0x00000041f16754 in Exiled.Events.Handlers.Player:OnDying (Exiled.Events.EventArgs.Player.DyingEventArgs)
[2023-09-23 09:58:24.017 +00:00] Game process exited and has been killed, no need to kill it.
[2023-09-23 09:58:24.017 +00:00] The game process has been terminated...
[2023-09-23 09:58:24.017 +00:00] --- END OF LOG ---
```

**To Reproduce**
Idk

**EXILED Version ("latest" is not a version):**
 8.2.1

**Comment by IRacle1** [comment]
Player_Statistic is your own plugin? Looks like thats not exiled error

**Comment by A-z-z-y** [comment]
The crash seems to result from Exiled though, as shown by the last entry in the stack trace.

**Comment by ITeMbI4** [comment]
> Player_Statistic is your own plugin? Looks like thats not exiled error

Yes, it's mine, but there is just logging, and stack trace show an error also in Exiled

**Comment by joker-119** [comment]
Just because the stack trace contains Exiled does not mean the error is Exiled's fault.

By that logic, all errors are basegame errors because basegame appears in the stack trace.

Errors are typically the result of the highest namespace on the stacktrace, not the lowest.

Exiled calls event -> Plugin processes event -> error occurs in processing

Stack trace will look like:
Exception (at) SomePlugin.EventHandlerThing
at Exiled.Events.Handlers.SomeEvent
as Some.Basegame.Method


The fault is the plugin, not exiled.

**Comment by ITeMbI4** [comment]
Hm, ok
