### ISSUE TITLE
[BUG] MirrorExtensions.SendFakeTargetRpc sometimes crash a server

### ISSUE THREAD

**Issue by ITeMbI4** [Exiled-Team/EXILED#2127]
**Describe the bug**
MirrorExtensions.SendFakeTargetRpc crash a server when `ev.Player.PlayBeepSound()` is used

**Server logs**
```
[2023-10-01 19:41:36.094 +00:00] [STDOUT] Caught fatal signal - signo:11 code:1 errno:0 addr:0x7f16e2a50d58
[2023-10-01 19:41:36.099 +00:00] [STDOUT] Obtained 15 stack frames.
[2023-10-01 19:41:36.099 +00:00] [STDOUT] #0  0x007f1887f66140 in funlockfile
[2023-10-01 19:41:36.099 +00:00] [STDOUT] #1  0x007f188180189f in GC_mark_from
[2023-10-01 19:41:36.099 +00:00] [STDOUT] #2  0x007f18817fc8c4 in GC_mark_some
[2023-10-01 19:41:36.099 +00:00] [STDOUT] #3  0x007f18817fc5e8 in GC_collect_a_little_inner
[2023-10-01 19:41:36.099 +00:00] [STDOUT] #4  0x007f18817fe06b in GC_allocobj
[2023-10-01 19:41:36.099 +00:00] [STDOUT] #5  0x007f18817f8465 in GC_generic_malloc_inner
[2023-10-01 19:41:36.099 +00:00] [STDOUT] #6  0x007f18817fe999 in GC_generic_malloc
[2023-10-01 19:41:36.099 +00:00] [STDOUT] #7  0x007f188180294d in GC_malloc_kind_global
[2023-10-01 19:41:36.099 +00:00] [STDOUT] #8  0x007f18817ccceb in mono_gc_register_root
[2023-10-01 19:41:36.099 +00:00] [STDOUT] #9  0x007f1881777a40 in mono_array_new_full
[2023-10-01 19:41:36.099 +00:00] [STDOUT] #10 0x007f1881799b43 in mono_verify_corlib
[2023-10-01 19:41:36.099 +00:00] [STDOUT] #11 0x007f1881721c8d in mono_install_unhandled_exception_hook
[2023-10-01 19:41:36.099 +00:00] [STDOUT] #12 0x007f188172fce8 in mono_lookup_icall_symbol
[2023-10-01 19:41:36.099 +00:00] [STDOUT] #13 0x000000417500be in (wrapper managed-to-native) System.Array:CreateInstanceImpl (System.Type,int[],int[])
[2023-10-01 19:41:36.099 +00:00] [STDOUT] #14 0x0000004210f834 in Exiled.API.Extensions.MirrorExtensions:SendFakeTargetRpc (Exiled.API.Features.Player,Mirror.NetworkIdentity,System.Type,string,object[])
[2023-10-01 19:41:36.202 +00:00] Game process exited and has been killed, no need to kill it.
[2023-10-01 19:41:36.202 +00:00] The game process has been terminated...
[2023-10-01 19:41:36.202 +00:00] --- END OF LOG ---
```

**EXILED Version ("latest" is not a version):**
[8.2.1](https://github.com/Exiled-Team/EXILED/tree/8.2.1)

**Comment by louis1706** [comment]
@ITeMbI4  can you said wish Rôle the player was having when you did send the BeepSound ?

**Comment by ITeMbI4** [comment]
> @ITeMbI4 can you said wish Rôle the player was having when you did send the BeepSound ?

There was 8 people on the server (mostly ClassD)

**Comment by louis1706** [comment]
Can you PM me on discord i have so question about how to reproduce

**Comment by louis1706** [comment]
This type of issue only hapen if you send it to a disconect player
